---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1uvmhawdljv3rdc9qvtq732cyrd235st2x9nd89m9k89pqk3hpg8q76t0am"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1uvmhawdljv3rdc9qvtq732cyrd235st2x9nd89m9k89pqk3hpg8q76t0am"
stores:
  yaml:
    indent: 2
